### ISSUE TITLE
Option to make exclusive for high health enemies maybe?

### ISSUE THREAD

**Issue by King597** [EladNLG/UltrakillHealthbars#1]
I like this mod a lot :) Would it be possible to make it so that it only activates for enemies above a certain max health, because I find adding a healthbar above a stray, for example, sort of just adds visual clutter (especially in Cybergrind). Really useful for mindflayers and such though. Thank you for making this mod and I hope u consider my suggestion. <3

**Comment by EladNLG** [comment]
Hey, this is a great suggestion and i will be looking into this.

**Comment by EladNLG** [comment]
Added in 1.2
